### ISSUE TITLE
Mumble image broken

### ISSUE THREAD

**Issue by tinyoverflow** [pelican-eggs/yolks#258]
Hello,

the current Mumble image is broken. The last working image is:
ghcr.io/parkervcp/yolks:voice_mumble@sha256:1409d49ca894f5f5f69355fe90e6d3afff62ed28be48f60b0781c1a0327e7524

In newer images, the mumble-server fails to start with:
```Error relocating /usr/bin/mumble-server: _ZN6google8protobuf8internal17AssignDescriptorsEPFPKNS1_15DescriptorTableEvEPN4absl12lts_202308029once_flagERKNS0_8MetadataE: symbol not found```

As the Dockerfile for this image wasn't updated for about four months now, I suspect a newer build of murmur inside the package repository. Maybe I'm on the wrong path, but the latest build inside the package repository is from April 2024:
https://pkgs.alpinelinux.org/packages?name=murmur&branch=edge&repo=&arch=&maintainer=

**Comment by QuintenQVD0** [comment]
#254 Is already there to fix that, for now use `quintenqvd/pterodactyl_images:temp_mumble` as that is a builded version of the one in the PR
